In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("IMDb Movies India.csv",encoding="latin1")

In [3]:
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,Drama,NaN,NaN,J.S. Randhawa,Manmauji,Birbal,Rajendra Bhatia
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,Drama,7.0,8,Gaurav Bakshi,Rasika Dugal,Vivek Ghamande,Arvind Jangid
2,#Homecoming,(2021),90 min,"Drama, Musical",NaN,NaN,Soumyajit Majumdar,Sayani Gupta,Plabita Borthakur,Roy Angana
3,#Yaaram,(2019),110 min,"Comedy, Romance",4.4,35,Ovais Khan,Prateik,Ishita Raj,Siddhant Kapoor
4,...And Once Again,(2010),105 min,Drama,NaN,NaN,Amol Palekar,Rajat Kapoor,Rituparna Sengupta,Antara Mali
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,(1988),NaN,Action,4.6,11,Mahendra Shah,Naseeruddin Shah,Sumeet Saigal,Suparna Anand
15505,Zulmi,(1999),129 min,"Action, Drama",4.5,655,Kuku Kohli,Akshay Kumar,Twinkle Khanna,Aruna Irani
15506,Zulmi Raj,(2005),NaN,Action,NaN,NaN,Kiran Thej,Sangeeta Tiwari,NaN,NaN
15507,Zulmi Shikari,(1988),NaN,Action,NaN,NaN,NaN,NaN,NaN,NaN
15508,Zulm-O-Sitam,(1998),130 min,"Action, Drama",6.2,20,K.C. Bokadia,Dharmendra,Jaya Prada,Arjun Sarja

In [4]:
df.head()
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15509 entries, 0 to 15508
Data columns (total 10 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      15509 non-null  object
 1   Year      14981 non-null  object
 2   Duration  7240 non-null   object
 3   Genre     13632 non-null  object
 4   Rating    7919 non-null   float64
 5   Votes     7920 non-null   object
 6   Director  14984 non-null  object
 7   Actor 1   13892 non-null  object
 8   Actor 2   13125 non-null  object
 9   Actor 3   12365 non-null  object
dtypes: float64(1), object(9)
memory usage: 1.2+ MB

Name           0
Year         528
Duration    8269
Genre       1877
Rating      7590
Votes       7589
Director     525
Actor 1     1617
Actor 2     2384
Actor 3     3144
dtype: int64

In [9]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
for col in ["Genre", "Director", "Actor 1", "Actor 2", "Actor 3"]:
    df[col] = le.fit_transform(df[col])
df

,Name,Year,Duration,Genre,Rating,Votes,Director,Actor 1,Actor 2,Actor 3
0,,NaN,NaN,299,NaN,NaN,1926,2250,800,3108
1,#Gadhvi (He thought he was Gandhi),(2019),109 min,299,7.0,8,1548,3280,4790,527
2,#Homecoming,(2021),90 min,351,NaN,NaN,5123,3713,2866,3450
3,#Yaaram,(2019),110 min,228,4.4,35,3319,2917,1504,4020
4,...And Once Again,(2010),105 min,299,NaN,NaN,385,3112,3462,405
...,...,...,...,...,...,...,...,...,...,...
15504,Zulm Ko Jala Doonga,(1988),NaN,0,4.6,11,2690,2586,4299,4262
15505,Zulmi,(1999),129 min,40,4.5,655,2499,227,4532,519
15506,Zulmi Raj,(2005),NaN,0,NaN,NaN,2424,3609,4891,4820
15507,Zulmi Shikari,(1988),NaN,0,NaN,NaN,5938,4718,4891,4820
15508,Zulm-O-Sitam,(1998),130 min,40,6.2,20,2195,1139,1589,490

In [14]:
print(df["Rating"].isnull().sum())

7590

In [15]:
df['Rating']=df['Rating'].fillna(df['Rating'].mean())
df['Rating']

0        5.841621
1        7.000000
2        5.841621
3        4.400000
4        5.841621
           ...
15504    4.600000
15505    4.500000
15506    5.841621
15507    5.841621
15508    6.200000
Name: Rating, Length: 15509, dtype: float64

In [16]:
print(df["Rating"].isnull().sum())

0

In [17]:
X = df[["Genre", "Director", "Actor 1", "Actor 2", "Actor 3"]]
Y=df['Rating']

In [21]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

In [22]:
X_train.head()

       Genre  Director  Actor 1  Actor 2  Actor 3
3485     361      2696     4215     2470     3842
8701     313      2534     2189      139     1832
11179    299      4332      993     4538     1145
11628    299      4871     1603     2785     1969
4819     299       415     4120     3871     2483

In [23]:
X_test.head()

       Genre  Director  Actor 1  Actor 2  Actor 3
11115    331      3243     4718     4891     4820
2921     299      3771     2510     3421     4726
3463     485        19     4718     4891     4820
2495     485      1061      847      921     4457
15263    479      5938     4718     4891     4820

In [24]:
Y_test.head()

11115    5.841621
2921     6.800000
3463     5.841621
2495     5.841621
15263    5.841621
Name: Rating, dtype: float64

In [25]:
Y_train.head()

3485     4.700000
8701     5.200000
11179    3.600000
11628    7.600000
4819     5.841621
Name: Rating, dtype: float64

In [26]:
from sklearn.linear_model import LinearRegression

In [27]:
model=LinearRegression()

In [29]:
model.fit(X_test,Y_test)

LinearRegression()

In [30]:
Y_pred=model.predict(X_test)

In [31]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [32]:
r2_score(Y_test,Y_pred)

0.008747531203824654

In [33]:
mean_squared_error(Y_test,Y_pred)

0.9540580725913798

In [34]:
mean_absolute_error(Y_test,Y_pred)

0.5956554225281745