In [92]:
import pandas as pd

In [93]:
df=pd.read_csv("advertising.csv")

In [94]:
print(df.head())

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [95]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   TV         200 non-null    float64
 1   Radio      200 non-null    float64
 2   Newspaper  200 non-null    float64
 3   Sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB
None

In [96]:
df[['TV','Radio','Newspaper','Sales']]

        TV  Radio  Newspaper  Sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3   12.0
3    151.5   41.3       58.5   16.5
4    180.8   10.8       58.4   17.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1   14.0
197  177.0    9.3        6.4   14.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   18.4

[200 rows x 4 columns]

In [97]:
df[['TV','Radio','Newspaper','Sales']].isnull().sum()

TV           0
Radio        0
Newspaper    0
Sales        0
dtype: int64

In [98]:
X=df[['TV','Radio','Newspaper']]

In [99]:
Y=df[['Sales']]

In [100]:
from sklearn.model_selection import train_test_split

In [101]:
X_test,X_train,Y_test,Y_train=train_test_split(X,Y,test_size=0.2,random_state=42)

In [102]:
from sklearn.linear_model import LinearRegression

In [103]:
model=LinearRegression()

In [104]:
model.fit(X_train,Y_train)

LinearRegression()

In [105]:
Y_pred=model.predict(X_test)

In [106]:
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [107]:
MSE=mean_squared_error(Y_test,Y_pred)

In [108]:
MAE=mean_absolute_error(Y_test,Y_pred)

In [109]:
r2=r2_score(Y_test,Y_pred)

In [110]:
print("MSE:",MSE)

MSE: 3.0036983167095097

In [111]:
print("MAE:",MAE)

MAE: 1.2867335934388993

In [112]:
print("R2score:",r2)

R2score: 0.8879190891395372

In [113]:
print(Y_test.shape)
print(Y_pred.shape)

(160, 1)
(160, 1)

In [114]:
comparison = pd.DataFrame({
    'Actual': Y_test.values.ravel(),
    'Predicted': Y_pred.ravel()
})

print(comparison.head())

   Actual  Predicted
0    11.0  11.164483
1    14.8  14.760357
2    10.1   9.601324
3     9.7   8.931320
4    16.6  16.348274